name: CI - Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 先确保能绿，再做格式/静态检查
      - name: Run tests
        run: python -m pytest -q

      # 测试已绿，再做质量检查（如需可把这两步上移）
      - name: Lint (flake8)
        run: make lint

      - name: Format check (black --check)
        run: make format-check
